# Generated by Django 3.1.8 on 2021-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210429_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Email Confirmation Date'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationcode',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date generated'),
        ),
    ]
