# Generated by Django 3.1.8 on 2021-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20210429_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='for_jeremy',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmation_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Email Confirmation Date'),
        ),
    ]
